### PR TITLE
stretch complete

### PR DESCRIPTION
**Pull request by eeerie**

### CODE REVIEW

**Comment by rbrooks6** [comment]
I think some .idea/ files got added in here by accident. Can you delete those and just leave the files under pipeline/ ?I think you can remove files from the github UI, so you might not even need to make a new commit

**Comment by eeerie** [comment]
Just deleted them! hopefully it worked.

**Review by vingkan — APPROVED** [review]
Looks great! Well done, Luke!

**Review by rbrooks6 — APPROVED** [review]
Excellent job!!

**Comment by rbrooks6** [comment]
You can go ahead and squash and merge and then close out the related issue! Great job @eeerie !

**Pull request merged**
